sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t edatondev/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true edatondev/docker-react npm run test
